[package]
name = "isa-l"
edition = "2021"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
build = "build.rs"

[lib]
# ISA-L doesn't use doctests.  Not yet, at least.
doctest = false

[dependencies]
