freebsd_instance:
  image_family: freebsd-11-4-snap

setup: &SETUP
  env:
    HOME: /tmp # cargo needs it
    RUST_BACKTRACE: full  # Better info for debugging test failures.
    # Temporary workaround for https://github.com/rust-lang/rustup/issues/2774
    RUSTUP_IO_THREADS: 1
  setup_script:
    - pkg install -y c-blosc isa-l fusefs-libs pkgconf
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal
    - $HOME/.cargo/bin/rustup toolchain install $VERSION
    # In 11.4, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1

task:
  matrix:
    - name: cargo test (nightly)
      env:
        VERSION: nightly
        CARGO_ARGS: --all-features
    - name: cargo test (stable)
      env:
        VERSION: 1.54.0
  << : *SETUP
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION build $CARGO_ARGS --all
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test $CARGO_ARGS --all --all-targets
  fuseless_script:
    - . $HOME/.cargo/env
    - cd bfffs
    - cargo +$VERSION check --no-default-features --all-targets
  release_script:
    # Release builds are too slow, and differ little from debug builds.  Just
    # check that it would compile, but don't try to build it.
    - . $HOME/.cargo/env
    - cargo +$VERSION check $CARGO_ARGS --release --all --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index

clippy_task:
  name: clippy
  env:
    VERSION: nightly
    CARGO_ARGS: --all-features
  << : *SETUP
  cargo_cache:
    folder: $HOME/.cargo/registry
  lint_script:
    - . $HOME/.cargo/env
    - $HOME/.cargo/bin/rustup component add --toolchain $VERSION clippy
    # Suppress clippy::nonstandard_macro_braces due to a clippy bug.
    # https://github.com/rust-lang/rust-clippy/issues/7434
    - cargo +$VERSION clippy --all-features --all-targets -- -D warnings -A clippy::nonstandard_macro_braces
  before_cache_script: rm -rf $CARGO_HOME/registry/index
