freebsd_instance:
  image: freebsd-11-3-stable-amd64-v20190801

test_task:
  name: cargo test 
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
    - $HOME/.cargo/bin/rustup toolchain install 1.36.0
    - $HOME/.cargo/bin/rustup toolchain install nightly
    # In 11.3, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  cargo_cache:
    folder: $CARGO_HOME/registry
  nightly_build_script:
    - cargo +nightly build --all-features --all
  stable_build_script:
    - cargo +stable build --all
  nightly_test_script:
    - cargo test --all-features --all --all-targets
  stable_test_script:
    - cargo test --all
  before_cache_script: rm -rf $CARGO_HOME/registry/index
