freebsd_instance:
  image_family: freebsd-11-4-snap

task:
  env:
    HOME: /tmp # cargo needs it
    # Temporary workaround for https://github.com/rust-lang/rustup/issues/2774
    RUSTUP_IO_THREADS: 1
  matrix:
    - name: cargo test (nightly)
      env:
        VERSION: nightly
        CARGO_ARGS: --all-features
    - name: cargo test (stable)
      env:
        VERSION: 1.52.0
  setup_script:
    - pkg install -y c-blosc isa-l fusefs-libs pkgconf
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal
    - $HOME/.cargo/bin/rustup toolchain install $VERSION
    # In 11.4, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION build $CARGO_ARGS --all
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test $CARGO_ARGS --all --all-targets
  fuseless_script:
    - . $HOME/.cargo/env
    - cd bfffs
    - cargo +$VERSION check --no-default-features --all-targets
  release_script:
    # Release builds are too slow, and differ little from debug builds.  Just
    # check that it would compile, but don't try to build it.
    - . $HOME/.cargo/env
    - cargo +$VERSION check $CARGO_ARGS --release --all --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index
