[package]
name = "arkfs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]

[features]
# Make mockers optional so we can still compile on stable
mocks = ["mockers", "mockers_codegen", "mockers_macros"]

[dependencies]
bytes = "0.4.5"
fixedbitset = "0.1.8"
futures = "0.1.14"
isa-l = { path = "isa-l" }
# mockers should be a dev dependency, but can't because of issue 1596
# https://github.com/rust-lang/cargo/issues/1596
mockers_codegen = { version = "=0.9.0", optional = true }
mockers_macros = { version = "=0.9.0", optional = true }
mockers = { version = "=0.9.0", optional = true }
# modulo is an RFC for addition to libstd
# https://github.com/rust-lang/rfcs/pull/2169
# If it gets merged, we can remove this crate
modulo = "0.1.2"
nix = "0.10.0"
tokio-file = { path = "/home/somers/src/rust/tokio-file" }
tokio-core = { path = "/home/somers/src/rust/tokio-core" }

[dev-dependencies]
galvanic-test = "0.1.3"
itertools = "0.7.1"
rand = "0.3"
tempdir = "0.3"

[workspace]
members = ["isa-l"]
