[package]
name = "arkfs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]

[features]
# Make mockers optional so we can still compile on stable
mocks = ["mockers", "mockers_codegen", "mockers_macros"]

[dependencies]
byteorder = "1.0"
divbuf = { git = "https://github.com/asomers/divbuf", rev = "0ca406c" }
fixedbitset = "0.1.8"
futures = "0.1.14"
itertools = "0.7"
isa-l = { path = "isa-l" }
lazy_static = "1.0"
metrohash = "1.0"
# mockers should be a dev dependency, but can't because of issue 1596
# https://github.com/rust-lang/cargo/issues/1596
mockers_codegen = { version = "=0.9.4", optional = true }
mockers_macros = { version = "=0.9.4", optional = true }
mockers = { version = "=0.9.4", optional = true }
# modulo is an RFC for addition to libstd
# https://github.com/rust-lang/rfcs/pull/2169
# If it gets merged, we can remove this crate
modulo = "0.1.2"
nix = { git = "https://github.com/nix-rust/nix", rev = "31e901b" }
serde = "1.0"
serde_cbor = "0.8"
serde_derive = "1.0"
tokio-file = { git = "https://github.com/asomers/tokio-file", rev = "4e2ed55" }
tokio = "0.1.4"
uuid = { version = "0.6", features = ["serde", "v4"]}

[dev-dependencies]
galvanic-test = "0.1.3"
itertools = "0.7.1"
permutohedron = "0.2"
rand = "0.3"
tempdir = "0.3"

[profile.bench]
lto = true

[profile.release]
lto = true

[workspace]
members = ["isa-l"]
