[profile.bench]
lto = true

[profile.release]
debug = true
lto = true

[workspace]
members = ["bfffs-core", "bfffs-fio", "bfffs", "isa-l"]

[patch.crates-io]
nix = { git = "https://github.com/asomers/nix.git", rev = "2e37293877b97eae42b1ec06a09e437b96b69c07" }
