[profile.bench]
debug = true
lto = true

[profile.release]
debug = true
lto = true

[workspace]
members = ["bfffs-core", "bfffs-fio", "bfffs", "isa-l"]

[patch.crates-io]
mockall = { git = "https://github.com/asomers/mockall.git", rev = "8af28ef" }
mockall_double = { git = "https://github.com/asomers/mockall.git", rev = "8af28ef" }
