[package]
name = "bfffs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]

[features]
# Make mockers optional so we can still compile on stable
mocks = ["mockers", "mockers_derive"]

[dependencies]
atomic = "0.3"
bincode = { version = "1.0.1", features = ["i128"] }
bitfield = "0.13"
blosc = "0.1"
byteorder = "1.2.3"
divbuf = { git = "https://github.com/asomers/divbuf/", rev = "9d9bc62" }
downcast = "0.8"
enum-primitive-derive = "^0.1"
env_logger = "0.5"
fixedbitset = "0.1.8"
fuse = "0.3"
futures = "0.1.14"
futures-locks = "0.1.1"
itertools = "0.7"
isa-l = { path = "isa-l" }
lazy_static = "1.0"
libc = "0.2.42"
metrohash = "1.0"
# mockers should be a dev dependency, but can't because of issue 1596
# https://github.com/rust-lang/cargo/issues/1596
mockers = { version = "=0.11.1", optional = true }
mockers_derive = { version = "=0.11.1", optional = true }
# modulo is available in nightly libstd only.  Once it stabilizes, we can
# remove this crate.
# https://github.com/rust-lang/rust/issues/49048
modulo = "0.1.2"
nix = "0.11.0"
num-traits = "^0.1"
serde = "1.0.60"
serde_cbor = "0.8"
serde_derive = "1.0"
time = "0.1"	# needed for FUSE
tokio = "0.1.7"
tokio-file = "0.3.0"
tokio-io-pool = "0.1"
uuid = { version = "0.6", features = ["serde", "v4"]}

[dependencies.clap]
version = "2"
default-features = false
features=  [ "suggestions", "color", "wrap_help" ]

[dev-dependencies]
galvanic-test = "0.1.3"
itertools = "0.7.1"
permutohedron = "0.2"
pretty_assertions = "0.5"
rand = "0.3"
serde_yaml = "0.7"
simulacrum = { version = "=0.3.0" }
tempdir = "0.3"

[profile.bench]
lto = true

[profile.release]
lto = true

[workspace]
members = ["isa-l"]

[patch.crates-io]
simulacrum_mock = { git = "https://github.com/asomers/simulacrum/", rev = "4be48c4" }
bitfield = { git = "https://github.com/dzamlo/rust-bitfield.git", rev = "233c81a" }
