[package]
name = "arkfs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]

[dependencies]
fixedbitset = "0.1.8"
futures = "0.1.14"
isa-l = { path = "isa-l" }
nix = { path = "/home/somers/src/rust/nix" }
tokio-file = { path = "/home/somers/src/rust/tokio-file" }
tokio-core = { path = "/home/somers/src/rust/tokio-core" }

[dev-dependencies]
galvanic-test = "0.1.3"
itertools = "0.7.1"
rand = "0.3"
tempdir = "0.3"

[workspace]
members = ["isa-l"]
