[profile.bench]
lto = true

[profile.release]
debug = true
lto = true

[workspace]
members = ["bfffs-core", "bfffs-fio", "bfffs", "isa-l"]

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio", rev = "957ed3e"  }

