[profile.bench]
lto = true

[profile.release]
debug = true
lto = true

[workspace]
members = ["bfffs", "isa-l"]
#members = ["bfffs", "bfffs-fio", "bfffs-fuse", "isa-l"]

[patch.crates-io]
futures-test = { git = "http://github.com/rust-lang/futures-rs.git", rev = "66949b88821543878ed18cf3f5d26ad5ab13cdb2" }
