[profile.bench]
lto = true

[profile.release]
debug = true
lto = true

[workspace]
members = ["bfffs", "bfffs-fuse", "isa-l"]

[patch.crates-io]
simulacrum_mock = { git = "https://github.com/pcsm/simulacrum/", rev = "13416e9" }
