[package]
name = "bfffs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[lib]
# BFFFS doesn't use doctests, because it's not a real library.
doctest = false

[features]
nightly = [ "mockall/nightly" ]

[dependencies]
async-trait = "0.1.40"
bincode = { version = "1.0.1", features = ["i128"] }
bitfield = "0.13.1"
blosc = "0.1.3"
byteorder = "1.2.3"
cfg-if = "1.0"
divbuf = { git = "https://github.com/asomers/divbuf.git", rev = "0a72fb5"}
downcast = "0.10.0"
enum-primitive-derive = "^0.1"
fixedbitset = "0.1.8"
futures = "0.3.0"
futures-locks = "0.6.0"
itertools = "0.7"
isa-l = { path = "../isa-l" }
lazy_static = "1.0"
libc = "0.2.44"
metrohash = "1.0"
mockall_double = "0.1.0"
nix = { git = "https://github.com/asomers/nix", rev = "7912d9cfb10ea3a8118f00eb5a40790cdea33c8d" }
num-traits = "^0.1"
serde = "1.0.60"
serde_derive = "1.0"
serde_yaml = "0.8.6"
time = "0.1"
tokio = { version = "0.2.7", features = ["rt-threaded", "sync", "time"] }
tokio-file = { git = "https://github.com/asomers/tokio-file", rev = "5dbb35cb4cbb5ff55faa6063426af1a04c363ad6" }
uuid = { version = "0.7", features = ["serde", "v4"]}

[dependencies.clap]
version = "2"
default-features = false
features=  [ "suggestions", "color", "wrap_help" ]

[dev-dependencies]
chashmap = "2"
env_logger = "0.5"
futures-test = "0.3.7"
galvanic-test = "0.2"
glob = "0.2"
histogram = "0.6"
itertools = "0.7.1"
log = "0.4"
mockall = { git = "https://github.com/asomers/mockall", rev = "1e6d98c735804092accbb74dc7380231cb4bd520" }
num_cpus = "1"
permutohedron = "0.2"
pretty_assertions = "0.5"
rand = "0.6"
rand_xorshift = "0.1"
tempfile = "3"
