[package]
name = "bfffs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[features]
default = ["fuse"]
fuse = ["fuse3"]

[[bin]]
name = "bfffsd"
required-features = ["fuse"]

[dependencies]
async-trait = "0.1.40"
bincode = "1.0.1"
bfffs-core = { path = "../bfffs-core" }
bytes = "1.0"
cfg-if = "1.0"
fuse3 = { git = "https://github.com/asomers/fuse3.git", rev = "3afd026", optional = true, features = ["tokio-runtime"] }
futures = "0.3.0"
libc = "0.2.44"
nix = "0.22.0"
time = { version = "0.3.0", features = [ "formatting" ] }
tokio = { version = "1.10.0", features = ["macros", "rt", "rt-multi-thread", "signal", "sync", "time"] }
tokio-seqpacket = "0.5.4"
tracing = "0.1.5"

[dependencies.clap]
version = "3.0.0-beta.4"
default-features = true
features=  [ "wrap_help"]

[dependencies.tracing-subscriber]
version = "0.2.15"
default-features = false
features = [ "ansi", "env-filter", "fmt", "tracing-log" ]

[dev-dependencies]
divbuf = { git = "https://github.com/asomers/divbuf.git", rev = "0a72fb5"}
mockall = "0.10.1"
rstest = "0.11.0"
