[package]
name = "bfffs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2021"

[features]
default = ["fuse"]
fuse = ["fuse3"]

[[bin]]
name = "bfffsd"
required-features = ["fuse"]

[dependencies]
async-trait = "0.1.40"
bincode = "1.0.1"
bfffs-core = { path = "../bfffs-core" }
bytes = "1.0"
cfg-if = "1.0"
fuse3 = { git = "https://github.com/asomers/fuse3.git", rev = "90f4c22", optional = true, features = ["tokio-runtime"] }
futures = "0.3.0"
libc = "0.2.44"
nix = { git = "http://github.com/nix-rust/nix", rev = "69738c0fd03af19053c5701a984f923ecbbfada6", default-features = false, features = ["user"] }
time = { version = "0.3.0", features = [ "formatting" ] }
tokio = { version = "1.10.0", features = ["macros", "rt", "rt-multi-thread", "signal", "sync", "time"] }
tokio-seqpacket = "0.5.4"
tracing = "0.1.5"

[dependencies.clap]
version = "3.1.0"
default-features = true
features=  [ "cargo", "derive", "wrap_help"]

[dependencies.tracing-subscriber]
version = "0.2.15"
default-features = false
features = [ "ansi", "env-filter", "fmt", "tracing-log" ]

[dev-dependencies]
assert_cmd = "2.0"
divbuf = { git = "https://github.com/asomers/divbuf.git", rev = "0a72fb5"}
freebsd-libgeom = "0.2.0"
function_name = "0.2.0"
mockall = "0.11.0"
nix = { git = "http://github.com/nix-rust/nix", rev = "69738c0fd03af19053c5701a984f923ecbbfada6", default-features = false, features = ["mount", "process", "signal", "user"] }
predicates = "2.1.0"
regex = "1.0"
rstest = "0.11.0"
si-scale = "0.1.0"
sysctl = "0.1"
tempfile = "3.2"

[[test]]
name = "integration"
path = "tests/integration/mod.rs"

[[bench]]
name = "bfffs-bench"
path = "benches/bfffs-bench/mod.rs"
harness = false
