[package]
name = "bfffs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[features]
default = ["fuse"]
fuse = ["fuse3"]

[[bin]]
name = "bfffsd"
required-features = ["fuse"]

[dependencies]
bfffs-core = { path = "../bfffs-core" }
cfg-if = "1.0"
fuse3 = { git = "https://github.com/Sherlock-Holo/fuse3.git", rev = "1f8605f", optional = true, features = ["tokio-runtime"] }
futures = "0.3.0"
libc = "0.2.44"
time = "0.1"
tokio = { version = "1.10.0", features = ["rt", "rt-multi-thread", "signal", "sync", "time"] }

[dependencies.clap]
version = "3.0.0-beta.4"
default-features = true
features=  [ "wrap_help"]

[dependencies.tracing-subscriber]
version = "0.2.15"
default-features = false
features = [ "ansi", "env-filter", "fmt", "tracing-log" ]

[dev-dependencies]
divbuf = { git = "https://github.com/asomers/divbuf.git", rev = "0a72fb5"}
mockall = "0.10.1"
rstest = "0.11.0"
