[package]
name = "bfffs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[lib]
# BFFFS doesn't use doctests, because it's not a real library.
doctest = false

[features]
# Make mockers optional so we can still compile on stable
nightly = ["mockers", "mockers_derive"]

[dependencies]
atomic = "0.3"
bincode = { version = "1.0.1", features = ["i128"] }
bitfield = "0.13.1"
blosc = { git = "https://github.com/asomers/blosc-rs/", rev = "04c9e02"}
byteorder = "1.2.3"
cfg-if = "0.1"
divbuf = { git = "https://github.com/asomers/divbuf.git", rev = "0a72fb5"}
downcast = "0.9.2"
enum-primitive-derive = "^0.1"
fixedbitset = "0.1.8"
fragile = "0.3"
futures = "0.1.14"
futures-locks = "0.3"
itertools = "0.7"
isa-l = { path = "../isa-l" }
lazy_static = "1.0"
libc = "0.2.44"
metrohash = "1.0"
# mockers should be a dev dependency, but can't because of issue 1596
# https://github.com/rust-lang/cargo/issues/1596
mockers = { version = "=0.12.2", optional = true }
mockers_derive = { version = "=0.12.2", optional = true }
# modulo is available in nightly libstd only.  Once it stabilizes, we can
# remove this crate.
# https://github.com/rust-lang/rust/issues/49048
modulo = "0.1.2"
nix = "0.12.0"
num-traits = "^0.1"
serde = "1.0.60"
serde_derive = "1.0"
serde_yaml = "0.8.6"
time = "0.1"
tokio = "0.1.8"
tokio-current-thread = "0.1.1"
tokio-file = "0.5.0"
tokio-io-pool = "0.1.4"
uuid = { version = "0.7", features = ["serde", "v4"]}

[dependencies.clap]
version = "2"
default-features = false
features=  [ "suggestions", "color", "wrap_help" ]

[dev-dependencies]
chashmap = "2"
env_logger = "0.5"
galvanic-test = "0.2"
glob = "0.2"
histogram = "0.6"
itertools = "0.7.1"
log = "0.4"
mockall = { git = "https://github.com/asomers/mockall/", rev = "322b002"}
num_cpus = "1"
permutohedron = "0.2"
predicates = "1.0"
pretty_assertions = "0.5"
rand = "0.6"
rand_xorshift = "0.1"
simulacrum = { version = "=0.3.0" }
tempdir = "0.3"
