[package]
name = "bfffs-fio"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"
# As a fio external ioengine, we must depend pretty intimately on fio's
# internals.  So this crate must be GPL-2 too.
license = "GPL-2.0"

[build-dependencies]
cc = "1.0"

[dependencies]
bfffs = { path = "../bfffs" }
futures = "0.3.0"
lazy_static = "1.0"
libc = "0.2.44"
memoffset = "0.5.1"
tokio = { version = "0.2.7", features = ["rt-threaded", "sync", "time"] }

[dependencies.tracing-subscriber]
version = "0.2.15"
default-features = false
features = [ "ansi", "env-filter", "fmt", "tracing-log" ]

[lib]
crate-type = ["cdylib"]
